import Handler from '../../handler/Handler';
import DragHandler from '../../handler/Drag';
import Map from '../Map';
import { Point } from './../../geo';
declare class MapDragHandler extends Handler {
    target: Map;
    _dragHandler: DragHandler;
    startDragTime: number;
    _mode: string;
    startBearing: number;
    preX: number;
    preY: number;
    startX: number;
    startY: number;
    _startPrjCenter: Point;
    startPrjCoord: Point;
    _rotateMode: string;
    _db: number;
    addHooks(): void;
    removeHooks(): void;
    _cancelOn(domEvent: any): boolean;
    _ignore(param: any): boolean;
    _onMouseDown(param: any): void;
    _onDragStart(param: any): void;
    _onDragging(param: any): void;
    _onDragEnd(param: any): void;
    _start(param: any): void;
    _moveStart(param: any): void;
    _moving(param: any): void;
    _moveEnd(param: any): void;
    _rotateStart(param: any): void;
    _rotating(param: any): void;
    _rotateEnd(param: any): void;
    _clear(): void;
}
export default MapDragHandler;
