type removeDPRListeningFunc = (map: any) => void;
type checkDevicePixelRatioFunc = () => boolean;
type addDPRListeningFunc = (map: any) => void;
type BrowserType = {
    edge?: boolean;
    ie?: boolean;
    ielt9?: boolean;
    ie9?: boolean;
    safari?: boolean;
    webkit?: boolean;
    phantomjs?: boolean;
    android?: boolean;
    android23?: boolean;
    chrome?: boolean;
    gecko?: boolean;
    iosWeixin?: boolean;
    mobile?: boolean;
    mobileWebkit?: boolean;
    mobileWebkit3d?: boolean;
    msPointer?: boolean;
    pointer?: boolean;
    ie3d?: boolean;
    webkit3d?: boolean;
    gecko3d?: boolean;
    opera12?: boolean;
    any3d?: boolean;
    imageBitMap?: boolean;
    resizeObserver?: boolean;
    btoa?: boolean;
    proxy?: boolean;
    touch?: boolean;
    retina?: boolean;
    webgl?: boolean;
    language?: string;
    chromeVersion?: string;
    devicePixelRatio: number;
    monitorDPRChange?: boolean;
    supportsPassive?: boolean;
    decodeImageInWorker?: boolean;
    removeDPRListening: removeDPRListeningFunc;
    checkDevicePixelRatio: checkDevicePixelRatioFunc;
    addDPRListening: addDPRListeningFunc;
};
declare let Browser: BrowserType;
export default Browser;
