import { registerWGSLSource } from '@maptalks/gl/src/reshader/gpu/WGSLSources';

// analysis
import analysisDepthFrag from '../../analysis/src/pass/wgsl/depth_frag.wgsl';
import analysisDepthVert from '../../analysis/src/pass/wgsl/depth_vert.wgsl';
import analysisExcavateExtentFrag from '../../analysis/src/pass/wgsl/excavateExtent_frag.wgsl';
import analysisExcavateExtentVert from '../../analysis/src/pass/wgsl/excavateExtent_vert.wgsl';
import analysisFloodFrag from '../../analysis/src/pass/wgsl/flood_frag.wgsl';
import analysisFloodVert from '../../analysis/src/pass/wgsl/flood_vert.wgsl';
import analysisInsightFrag from '../../analysis/src/pass/wgsl/insight_frag.wgsl';
import analysisInsightVert from '../../analysis/src/pass/wgsl/insight_vert.wgsl';
import analysisViewshedFrag from '../../analysis/src/pass/wgsl/viewshed_frag.wgsl';
import analysisViewshedVert from '../../analysis/src/pass/wgsl/viewshed_vert.wgsl';

// gl
import glAnalysisFrag from '../../gl/src/analysis/wgsl/analysis_frag.wgsl';
import glFillFrag from '../../gl/src/layer/glsl/fill_frag.wgsl';
import glFillVert from '../../gl/src/layer/glsl/fill_vert.wgsl';
import glTerrainFrag from '../../gl/src/layer/terrain/wgsl/terrain_frag.wgsl';
import glTerrainSkinFrag from '../../gl/src/layer/terrain/wgsl/terrain_skin_frag.wgsl';
import glTerrainSkinVert from '../../gl/src/layer/terrain/wgsl/terrain_skin_vert.wgsl';
import glTerrainVert from '../../gl/src/layer/terrain/wgsl/terrain_vert.wgsl';
import glStandardFrag from '../../gl/src/reshader/pbr/wgsl/standard_frag.wgsl';
import glStandardVert from '../../gl/src/reshader/pbr/wgsl/standard_vert.wgsl';
import glBloomCombineFrag from '../../gl/src/reshader/shader/wgsl/bloom_combine_frag.wgsl';
import glBlur0Frag from '../../gl/src/reshader/shader/wgsl/blur0_frag.wgsl';
import glBlur1Frag from '../../gl/src/reshader/shader/wgsl/blur1_frag.wgsl';
import glBlur2Frag from '../../gl/src/reshader/shader/wgsl/blur2_frag.wgsl';
import glBlur3Frag from '../../gl/src/reshader/shader/wgsl/blur3_frag.wgsl';
import glBlur4Frag from '../../gl/src/reshader/shader/wgsl/blur4_frag.wgsl';
import glBlur5Frag from '../../gl/src/reshader/shader/wgsl/blur5_frag.wgsl';
import glBlur6Frag from '../../gl/src/reshader/shader/wgsl/blur6_frag.wgsl';
import glBoxShadowBlurFrag from '../../gl/src/reshader/shader/wgsl/box_shadow_blur_frag.wgsl';
import glCopyDepthFrag from '../../gl/src/reshader/shader/wgsl/copy_depth_frag.wgsl';
import glCopyFrag from '../../gl/src/reshader/shader/wgsl/copy_frag.wgsl';
import glFxaaFrag from '../../gl/src/reshader/shader/wgsl/fxaa_frag.wgsl';
import glImageFrag from '../../gl/src/reshader/shader/wgsl/image_frag.wgsl';
import glImageVert from '../../gl/src/reshader/shader/wgsl/image_vert.wgsl';
import glPhongFrag from '../../gl/src/reshader/shader/wgsl/phong_frag.wgsl';
import glPhongVert from '../../gl/src/reshader/shader/wgsl/phong_vert.wgsl';
import glQuadFrag from '../../gl/src/reshader/shader/wgsl/quad_frag.wgsl';
import glQuadVert from '../../gl/src/reshader/shader/wgsl/quad_vert.wgsl';
import glShadowDisplayFrag from '../../gl/src/reshader/shadow/wgsl/shadow_display_frag.wgsl';
import glShadowDisplayVert from '../../gl/src/reshader/shadow/wgsl/shadow_display_vert.wgsl';
import glVsmMappingFrag from '../../gl/src/reshader/shadow/wgsl/vsm_mapping_frag.wgsl';
import glVsmMappingVert from '../../gl/src/reshader/shadow/wgsl/vsm_mapping_vert.wgsl';
import glSkyboxFrag from '../../gl/src/reshader/skybox/skybox_frag.wgsl';
import glSkyboxVert from '../../gl/src/reshader/skybox/skybox_vert.wgsl';

// 3dtiles
import layer3dtilesPickingVert from '../../layer-3dtiles/src/layer/renderer/wgsl/picking_vert.wgsl';

// video
import layerVideoVideoFrag from '../../layer-video/src/video_frag.wgsl';
import layerVideoVideoVert from '../../layer-video/src/video_vert.wgsl';

// vt
import vtBillboardFrag from '../../vt/src/layer/plugins/painters/wgsl/billboard_frag.wgsl';
import vtBillboardVert from '../../vt/src/layer/plugins/painters/wgsl/billboard_vert.wgsl';
import vtCollisionFrag from '../../vt/src/layer/plugins/painters/wgsl/collision_frag.wgsl';
import vtCollisionVert from '../../vt/src/layer/plugins/painters/wgsl/collision_vert.wgsl';
import vtFillFrag from '../../vt/src/layer/plugins/painters/wgsl/fill_frag.wgsl';
import vtFillPickingVert from '../../vt/src/layer/plugins/painters/wgsl/fill_picking_vert.wgsl';
import vtFillVert from '../../vt/src/layer/plugins/painters/wgsl/fill_vert.wgsl';
import vtLineFrag from '../../vt/src/layer/plugins/painters/wgsl/line_frag.wgsl';
import vtLineGradientFrag from '../../vt/src/layer/plugins/painters/wgsl/line_gradient_frag.wgsl';
import vtLineVert from '../../vt/src/layer/plugins/painters/wgsl/line_vert.wgsl';
import vtMarkerFrag from '../../vt/src/layer/plugins/painters/wgsl/marker_frag.wgsl';
import vtMarkerVert from '../../vt/src/layer/plugins/painters/wgsl/marker_vert.wgsl';
import vtNativeLineFrag from '../../vt/src/layer/plugins/painters/wgsl/native-line_frag.wgsl';
import vtNativeLineVert from '../../vt/src/layer/plugins/painters/wgsl/native-line_vert.wgsl';
import vtNativePointFrag from '../../vt/src/layer/plugins/painters/wgsl/native-point_frag.wgsl';
import vtNativePointVert from '../../vt/src/layer/plugins/painters/wgsl/native-point_vert.wgsl';
import vtOutlineFrag from '../../vt/src/layer/plugins/painters/wgsl/outline_frag.wgsl';
import vtTextFrag from '../../vt/src/layer/plugins/painters/wgsl/text_frag.wgsl';
import vtTextLineVert from '../../vt/src/layer/plugins/painters/wgsl/text_line_vert.wgsl';
import vtTextVert from '../../vt/src/layer/plugins/painters/wgsl/text_vert.wgsl';
import vtTubeVert from '../../vt/src/layer/plugins/painters/wgsl/tube_vert.wgsl';

registerWGSLSource('analysis_depth_frag', analysisDepthFrag);
registerWGSLSource('analysis_depth_vert', analysisDepthVert);
registerWGSLSource('analysis_excavateExtent_frag', analysisExcavateExtentFrag);
registerWGSLSource('analysis_excavateExtent_vert', analysisExcavateExtentVert);
registerWGSLSource('analysis_flood_frag', analysisFloodFrag);
registerWGSLSource('analysis_flood_vert', analysisFloodVert);
registerWGSLSource('analysis_insight_frag', analysisInsightFrag);
registerWGSLSource('analysis_insight_vert', analysisInsightVert);
registerWGSLSource('analysis_viewshed_frag', analysisViewshedFrag);
registerWGSLSource('analysis_viewshed_vert', analysisViewshedVert);
registerWGSLSource('gl_analysis_frag', glAnalysisFrag);
registerWGSLSource('gl_fill_frag', glFillFrag);
registerWGSLSource('gl_fill_vert', glFillVert);
registerWGSLSource('gl_terrain_frag', glTerrainFrag);
registerWGSLSource('gl_terrain_skin_frag', glTerrainSkinFrag);
registerWGSLSource('gl_terrain_skin_vert', glTerrainSkinVert);
registerWGSLSource('gl_terrain_vert', glTerrainVert);
registerWGSLSource('gl_standard_frag', glStandardFrag);
registerWGSLSource('gl_standard_vert', glStandardVert);
registerWGSLSource('gl_bloom_combine_frag', glBloomCombineFrag);
registerWGSLSource('gl_blur0_frag', glBlur0Frag);
registerWGSLSource('gl_blur1_frag', glBlur1Frag);
registerWGSLSource('gl_blur2_frag', glBlur2Frag);
registerWGSLSource('gl_blur3_frag', glBlur3Frag);
registerWGSLSource('gl_blur4_frag', glBlur4Frag);
registerWGSLSource('gl_blur5_frag', glBlur5Frag);
registerWGSLSource('gl_blur6_frag', glBlur6Frag);
registerWGSLSource('gl_box_shadow_blur_frag', glBoxShadowBlurFrag);
registerWGSLSource('gl_copy_depth_frag', glCopyDepthFrag);
registerWGSLSource('gl_copy_frag', glCopyFrag);
registerWGSLSource('gl_fxaa_frag', glFxaaFrag);
registerWGSLSource('gl_image_frag', glImageFrag);
registerWGSLSource('gl_image_vert', glImageVert);
registerWGSLSource('gl_phong_frag', glPhongFrag);
registerWGSLSource('gl_phong_vert', glPhongVert);
registerWGSLSource('gl_quad_frag', glQuadFrag);
registerWGSLSource('gl_quad_vert', glQuadVert);
registerWGSLSource('gl_shadow_display_frag', glShadowDisplayFrag);
registerWGSLSource('gl_shadow_display_vert', glShadowDisplayVert);
registerWGSLSource('gl_vsm_mapping_frag', glVsmMappingFrag);
registerWGSLSource('gl_vsm_mapping_vert', glVsmMappingVert);
registerWGSLSource('gl_skybox_frag', glSkyboxFrag);
registerWGSLSource('gl_skybox_vert', glSkyboxVert);
registerWGSLSource('layer_3dtiles_picking_vert', layer3dtilesPickingVert);
registerWGSLSource('layer_video_video_frag', layerVideoVideoFrag);
registerWGSLSource('layer_video_video_vert', layerVideoVideoVert);
registerWGSLSource('vt_billboard_frag', vtBillboardFrag);
registerWGSLSource('vt_billboard_vert', vtBillboardVert);
registerWGSLSource('vt_collision_frag', vtCollisionFrag);
registerWGSLSource('vt_collision_vert', vtCollisionVert);
registerWGSLSource('vt_fill_frag', vtFillFrag);
registerWGSLSource('vt_fill_picking_vert', vtFillPickingVert);
registerWGSLSource('vt_fill_vert', vtFillVert);
registerWGSLSource('vt_line_frag', vtLineFrag);
registerWGSLSource('vt_line_gradient_frag', vtLineGradientFrag);
registerWGSLSource('vt_line_vert', vtLineVert);
registerWGSLSource('vt_marker_frag', vtMarkerFrag);
registerWGSLSource('vt_marker_vert', vtMarkerVert);
registerWGSLSource('vt_native_line_frag', vtNativeLineFrag);
registerWGSLSource('vt_native_line_vert', vtNativeLineVert);
registerWGSLSource('vt_native_point_frag', vtNativePointFrag);
registerWGSLSource('vt_native_point_vert', vtNativePointVert);
registerWGSLSource('vt_outline_frag', vtOutlineFrag);
registerWGSLSource('vt_text_frag', vtTextFrag);
registerWGSLSource('vt_text_line_vert', vtTextLineVert);
registerWGSLSource('vt_text_vert', vtTextVert);
registerWGSLSource('vt_tube_vert', vtTubeVert);
